spring.datasource.url=${AUTH_DB_URL:jdbc:mysql://localhost:3306/authpfee?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${AUTH_DB_USERNAME:root}
spring.datasource.password=${AUTH_DB_PASSWORD:}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.cloud.discovery.enabled=false
eureka.client.enabled=false

management.health.db.enabled=false
customer.service.url=${CUSTOMER_SERVICE_URL:http://localhost:8886}
