server.port=8887
server.servlet.context-path=/bank

spring.application.name=account-service

spring.datasource.url=jdbc:mysql://localhost:3306/comptebancairennn?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.cloud.discovery.enabled=false
eureka.client.enabled=false
axon.axonserver.enabled=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

application.security.jwt.secret=${JWT_SECRET:AaZzBbCcYyDdXxEeWwFf}
application.security.jwt.expiration=${JWT_EXPIRATION:604800000}
customer.service.url=${CUSTOMER_SERVICE_URL:http://localhost:8886}

management.endpoints.web.exposure.include=*
management.health.db.enabled=false
management.health.axon.enabled=false
