spring.datasource.url=${ACCOUNT_DB_URL:jdbc:mysql://localhost:3306/comptebancairennn?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${ACCOUNT_DB_USERNAME:root}
spring.datasource.password=${ACCOUNT_DB_PASSWORD:}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.cloud.discovery.enabled=false
eureka.client.enabled=false
axon.axonserver.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

management.health.db.enabled=false
management.health.axon.enabled=false

application.security.jwt.secret=${JWT_SECRET:AaZzBbCcYyDdXxEeWwFf}
application.security.jwt.expiration=${JWT_EXPIRATION:604800000}
customer.service.url=${CUSTOMER_SERVICE_URL:http://localhost:8886}
